apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: ingress-proxy
  name: ingress-proxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.ingress_proxy.deployment.replicas }}
  selector:
    matchLabels:
      gloo: ingress-proxy
  template:
    metadata:
      labels:
        gloo: ingress-proxy
{{- with .Values.ingress_proxy.deployment.extra_annotations }}
      annotations:
{{toYaml  . | indent 8}}{{- end }}
    spec:
      containers:
      - args: ["--disable-hot-restart"]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: "{{ .Values.ingress_proxy.deployment.image.repository }}:{{ .Values.ingress_proxy.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.ingress_proxy.deployment.image.pull_policy }}
        name: ingress-proxy
        ports:
        - containerPort: {{ .Values.ingress_proxy.deployment.http_port }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.ingress_proxy.deployment.https_port }}
          name: https
          protocol: TCP
{{- with .Values.ingress_proxy.deployment.extra_ports }}
{{toYaml  . | indent 8}}{{- end }}
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-config
      volumes:
      - configMap:
          name: ingress-envoy-config
        name: envoy-config