apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: gloo
  name: gloo
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.gloo.deployment.replicas }}
  selector:
    matchLabels:
      gloo: gloo
  template:
    metadata:
      labels:
        gloo: gloo
    spec:
      containers:
      - image: "{{ .Values.gloo.deployment.image.repository }}:{{ .Values.gloo.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.gloo.deployment.image.pull_policy }}
        name: gloo
        ports:
        - containerPort: {{ .Values.gloo.deployment.xds_port }}
          name: grpc
          protocol: TCP
        args: ["--namespace", "{{.Release.Namespace}}" ]
      {{- if .Values.gloo.deployment.image.pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.gloo.deployment.image.pull_secret }}{{end}}

