apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: discovery
  name: discovery
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.discovery.deployment.replicas }}
  selector:
    matchLabels:
      gloo: discovery
  template:
    metadata:
      labels:
        gloo: discovery
    spec:
      containers:
      - image: "{{ .Values.discovery.deployment.image.repository }}:{{ .Values.discovery.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.discovery.deployment.image.pull_policy }}
        name: discovery
        args: ["--namespace={{.Release.Namespace}}" ]

