apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
  name: gateway-proxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.gateway_proxy.deployment.replicas }}
  selector:
    matchLabels:
      gloo: gateway-proxy
  template:
    metadata:
      labels:
        gloo: gateway-proxy
{{- with .Values.gateway_proxy.deployment.extra_annotations }}
      annotations:
{{toYaml  . | indent 8}}{{- end }}
    spec:
      containers:
      - args: ["--disable-hot-restart"]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: {{ .Values.gateway_proxy.deployment.image.repository }}:{{ .Values.gateway_proxy.deployment.image.tag }}
        imagePullPolicy: {{ .Values.gateway_proxy.deployment.image.pull_policy }}
        name: gateway-proxy
        ports:
        - containerPort: {{ .Values.gateway_proxy.deployment.http_port }}
          name: http
          protocol: TCP
{{- with .Values.gateway_proxy.deployment.extra_ports }}
{{toYaml  . | indent 8}}{{- end }}
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-config
      {{- if .Values.gateway_proxy.deployment.image.pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.gateway_proxy.deployment.image.pull_secret }}{{end}}
      volumes:
      - configMap:
          name: gateway-envoy-config
        name: envoy-config