apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
  name: gateway-proxy
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.gateway_proxy.deployment.http_port }}
    protocol: TCP
    name: http
  selector:
    gloo: gateway-proxy
  type: LoadBalancer
