{{ if .Values.settings.create }}

apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  bindAddr: 0.0.0.0:9977
  discoveryNamespace: {{ .Values.settings.writeNamespace }}
  kubernetesArtifactSource: {}
  kubernetesConfigSource: {}
  kubernetesSecretSource: {}
  refreshRate: 60s
{{- with .Values.settings.watchNamespaces }}
  watchNamespaces:
  - {{ . }}
{{- end }}
{{- end }}

{{- end }}
