namespace:
  create: true
rbac:
  create: true

settings:
  integrations:
    knative:
      enabled: true
      proxy:
        image:
          repository: soloio/gloo-envoy-wrapper
          pullPolicy: Always
        httpPort: 80
        httpsPort: 443
        replicas: 1

  # namespaces that Gloo should watch. this includes watches set for pods, services, as well as CRD configuration objects
  watchNamespaces: []
  # the namespace that Gloo should write discovery data (Upstreams)
  writeNamespace: "gloo-system"

gloo:
  deployment:
    image:
      repository: soloio/gloo
      pullPolicy: Always
    xdsPort: 9977
    replicas: 1

discovery:
  deployment:
    image:
      repository: soloio/discovery
      pullPolicy: Always
    replicas: 1

gateway:
  deployment:
    image:
      repository: soloio/gateway
      pullPolicy: Always
    replicas: 1

gatewayProxy:
  deployment:
    image:
      repository: soloio/gloo-envoy-wrapper
      pullPolicy: Always
    httpPort: 8080
    replicas: 1
  configMap:
    data:

ingress:
  deployment:
    image:
      repository: soloio/ingress
      pullPolicy: Always
    replicas: 1

ingressProxy:
  deployment:
    image:
      repository: soloio/gloo-envoy-wrapper
      pullPolicy: Always
    httpPort: 80
    httpsPort: 443
    replicas: 1
  configMap:
    data:
