namespace:
  create: true
rbac:
  create: true

settings:
  integrations:
    knative:
      enabled: false
  # if this is set to false, default settings will be created by pods upon boot
  create: false
  # namespaces that Gloo should watch. this includes watches set for pods, services, as well as CRD configuration objects
  watchNamespaces: []
  # the namespace that Gloo should write discovery data (Upstreams)
  writeNamespace: "gloo-system"


# NEW


gloo:
  deployment:
    image:
      tag: 0.6.0
      repository: soloio/gloo
      pullPolicy: Always
    xdsPort: 9977
    replicas: 1

discovery:
  deployment:
    image:
      tag: 0.6.0
      repository: soloio/discovery
      pullPolicy: Always
    replicas: 1

gateway:
  deployment:
    image:
      tag: 0.6.0
      repository: soloio/gateway
      pullPolicy: Always
    replicas: 1

gatewayProxy:
  deployment:
    image:
      tag: 0.6.0
      repository: soloio/gloo-envoy-wrapper
      pullPolicy: Always
    httpPort: 8080
    replicas: 1
  configMap:
    data: ""


ingress:
  deployment:
    image:
      tag: 0.6.0
      repository: soloio/ingress
      pullPolicy: Always
    replicas: 1


ingressProxy:
  deployment:
    image:
      tag: 0.6.0
      repository: soloio/gloo-envoy-wrapper
      pullPolicy: Always
    http_port: 80
    https_port: 443
  config_map:
    envoy:
      static:
        listeners:
        clusters:

